# Generated by Django 5.0.1 on 2024-01-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_remove_starsystem_stars_star_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='weight',
        ),
    ]
